# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagz', '0002_auto_20160707_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chunks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tagz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('chunks', models.ManyToManyField(to='tagz.Chunks')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Tagz',
            field=models.ManyToManyField(to='tagz.Tagz'),
        ),
    ]
