# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagz', '0003_auto_20160707_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Tagz',
            new_name='tagz',
        ),
    ]
