# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagz', '0004_auto_20160707_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagz',
            name='chunks',
            field=models.ManyToManyField(blank=True, null=True, to='tagz.Chunks'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tagz',
            field=models.ManyToManyField(blank=True, null=True, to='tagz.Tagz'),
        ),
    ]
