# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 20:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tagz', '0005_auto_20160707_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunks',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 7, 20, 18, 24, 976719, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
